### ISSUE TITLE
add FBC logo

### ISSUE THREAD

**Issue by gwbostee** [gwbostee/FBC-project#5]
FBC logo should be visible somewhere on top

**Comment by GlennVM** [comment]
Left side of the menu is allocated for the logo, but the one we've got right now is just a png of the white letter. No red background

**Comment by gwbostee** [comment]
I already made one with a red background :) (it's not very beautiful but it is what it is...)

**Comment by GlennVM** [comment]
fixed in db379121960a5c8c690d1ab958ceeb823f31aafa
