### ISSUE TITLE
Sticky menu

### ISSUE THREAD

**Issue by gwbostee** [gwbostee/FBC-project#6]
The menu should be visible when scrolling down, for example stick to the top of the window.

**Comment by GlennVM** [comment]
The left side menu? We should think about where we want a menu.

Only on top, or also on the left?

**Comment by gwbostee** [comment]
Left side menu should be removed then.

**Comment by gwbostee** [comment]
I left the menu component in code for now...  I can still use it as an example

**Comment by GlennVM** [comment]
deleted in previous commit
